# Generated by Django 5.2.7 on 2025-12-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaEcuaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sistema sin nombre', max_length=200)),
                ('ecuaciones', models.TextField()),
                ('valores_iniciales', models.CharField(max_length=200)),
                ('tolerancia', models.FloatField()),
                ('max_iteraciones', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Iteracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valores', models.TextField()),
                ('errores', models.TextField()),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteraciones', to='interfaz.sistemaecuaciones')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.TextField()),
                ('variables', models.CharField(max_length=200)),
                ('convergio', models.BooleanField(default=True)),
                ('iteraciones_usadas', models.IntegerField()),
                ('sistema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interfaz.sistemaecuaciones')),
            ],
        ),
    ]
